services:
    inouire.password_resetting:
        class: Inouire\UserBundle\EventListener\RegisterUserListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

