<?php

namespace Inouire\MininetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository{
	
	/*
     * Get all the images of the posts of a given year
     */
    public function getImagesOfYear($year){
        
        $qb = $this->createQueryBuilder('image');
		  
		$qb->leftJoin('image.post','post')
		   ->addSelect('post')
		   ->where('post.date BETWEEN :yearBeginning AND :yearEnd')
           ->andWhere('post.published = true')
           ->setParameter('yearBeginning',  new \Datetime($year.'-01-01'))
           ->setParameter('yearEnd', new \Datetime($year.'-12-31 23:59:59'))
           ->orderBy('post.date', 'ASC');
           
        return $qb->getQuery()
                  ->getResult();
    }
}
