<?php

namespace Inouire\MininetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository{
    
    /*
     * Get all the videos
     */
    public function getAllVideos(){
        
        $qb = $this->createQueryBuilder('video');
          
        $qb->leftJoin('video.post','post')
           ->orderBy('post.date', 'DESC');
           
        return $qb->getQuery()
                  ->getResult();
    }
}
