# main routes
        
home:
    pattern:  /
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Default:home }
    
oldHome:
    pattern:  /home
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Default:oldHome }

archives:
    pattern:  /posts
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Archives:viewCurrentMonth }
    
posts:
    pattern:  /posts/{year}/{month}
    requirements:
        year:  \d+
        month: \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Archives:posts }
    
# galeries
    
albums:
    pattern:  /albums
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Album:viewCurrentMonthPicturesAlbum }
    
tag_list:
    pattern: /tags
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Tag:list }

album:
    pattern:  /album/{year}/{month}
    requirements:
        year:  \d+
        month: \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Album:viewPicturesAlbum }

tag_album:
    pattern: /album/{tag}
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Album:viewTagAlbum }

videos:
    pattern: /videos
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Album:viewVideosAlbum }


# routes for actions on posts

new_post:
    pattern:  /post/new
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Post:new }
    
view_post:
    pattern:  /post/{id}
    requirements:
        post_id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Post:view }   

edit_post:
    pattern:  /post/{id}/edit
    requirements:
        post_id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Post:edit }   
    
update_post:
    pattern: /post/update
    requirements:
        _method:  POST
    defaults: { _controller: InouireMininetBundle:Post:updateContent }
    
    
# routes for actions on comments

post_comment:
    pattern:  /comment
    requirements:
        _method:  POST
        _format:  json
    defaults: { _controller: InouireMininetBundle:Comment:postComment }

update_comment:
    pattern:  /comment/{id}
    requirements:
        _method:  POST
        _format:  json
    defaults: { _controller: InouireMininetBundle:Comment:updateComment }
    
delete_comment:
    pattern:  /comment/{id}
    requirements:
        comment_id:  \d+
        _method:  DELETE
        _format:  json
    defaults: { _controller: InouireMininetBundle:Comment:deleteComment }
    
# routes for actions on images

get_image:
    pattern:  /image/{id}.jpg
    requirements:
        id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Image:getImage}   

get_thumbnail:
    pattern:  /thumbnail/{id}
    requirements:
        id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Image:getImage, is_thumbnail: true}   
    
delete_image:
    pattern:  /image/{id}
    requirements:
        iid:  \d+
        _method:  DELETE
    defaults: { _controller: InouireMininetBundle:Image:deleteImage }  
     
rotate_image:
    pattern:  /image/{id}/rotate
    requirements:
        id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Image:rotateImage }
    
tag_image:
    pattern: /image/{id}/tag/{tag_id}
    requirements:
        id: \d+
        tag_id:   \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Tag:addTagToImage }
    
untag_image:
    pattern: /image/{id}/untag/{tag_id}
    requirements:
        id: \d+
        tag_id:   \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Tag:removeTagFromImage }

# routes for actions on videos

get_video:
    pattern:  /video/{id}
    requirements:
        id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Video:getVideo}   

get_video_thumbnail:
    pattern:  /video/thumbnail/{id}
    requirements:
        id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Video:getVideoThumbnail}  
    
delete_video:
    pattern:  /video/{id}
    requirements:
        id:  \d+
        _method:  DELETE
    defaults: { _controller: InouireMininetBundle:Video:deleteVideo } 

# routes for action towards sharing

create_sharelink:
    pattern: /post/{id}/share
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:ShareLink:new }   

get_sharelink:
    pattern: /public/{token}
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:ShareLink:get } 

get_sharelink_image:
    pattern: /public/{token}/image/{id}.jpg
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:ShareLink:getImage } 

get_sharelink_thumbnail:
    pattern: /public/{token}/thumbnail/{id}
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:ShareLink:getImage, is_thumbnail: true}   
    
get_sharelink_video:
    pattern: /public/{token}/video/{id}
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:ShareLink:getVideo } 

get_sharelink_video_thumbnail:
    pattern: /public/{token}/video/thumbnail/{id}
    requirements:
        _method:  GET
    defaults: { _controller: InouireMininetBundle:ShareLink:getVideoThumbnail}
