#main routes
home:
    pattern:  /
    defaults: { _controller: InouireMininetBundle:Default:home }
    
oldHome:
    pattern:  /home
    defaults: { _controller: InouireMininetBundle:Default:oldHome }

archives:
    pattern:  /posts
    defaults: { _controller: InouireMininetBundle:Archives:viewCurrentMonth }
    
posts:
    pattern:  /posts/{year}/{month}
    requirements:
        year:  \d+
        month: \d+
    defaults: { _controller: InouireMininetBundle:Archives:posts }
    
albums:
    pattern:  /albums
    defaults: { _controller: InouireMininetBundle:Album:viewCurrentMonth }
    
album:
    pattern:  /album/{year}/{month}
    requirements:
        year:  \d+
        month: \d+
    defaults: { _controller: InouireMininetBundle:Album:view }

export_content:
    pattern: /export/content
    defaults: 
        _controller: InouireMininetBundle:Export:content
        _format: txt
    
#routes for actions on posts
view_post:
    pattern:  /post/{post_id}
    requirements:
        post_id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Post:view }   
    
new_post:
    pattern:  /post/new
    defaults: { _controller: InouireMininetBundle:Post:new }

edit_post:
    pattern:  /post/{post_id}/edit
    requirements:
        post_id:  \d+
    defaults: { _controller: InouireMininetBundle:Post:edit }   
    
update_post:
    pattern: /post/update
    requirements:
        _method:  POST
    defaults: { _controller: InouireMininetBundle:Post:updateContent }
    
    
#routes for actions on comments
post_comment:
    pattern:  /comment
    requirements:
        _method:  POST
        _format:  json
    defaults: { _controller: InouireMininetBundle:Comment:postComment }

delete_comment:
    pattern:  /comment/{comment_id}
    requirements:
        comment_id:  \d+
        _method:  DELETE
        _format:  json
    defaults: { _controller: InouireMininetBundle:Comment:deleteComment }
    
update_comment:
    pattern:  /comment/{comment_id}
    requirements:
        _method:  POST
        _format:  json
    defaults: { _controller: InouireMininetBundle:Comment:updateComment }

#routes for actions on images
add_image:
    pattern:  /image
    requirements:
        _method:  POST
    defaults: { _controller: InouireMininetBundle:Image:addImage }   

get_image:
    pattern:  /image/{image_id}.jpg
    requirements:
        image_id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Image:getImage }   

delete_image:
    pattern:  /image/{image_id}.jpg
    requirements:
        image_id:  \d+
        _method:  DELETE
    defaults: { _controller: InouireMininetBundle:Image:deleteImage }  
     
rotate_image:
    pattern:  /image/{image_id}.jpg/rotate
    requirements:
        image_id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Image:rotateImage }
