parameters:
    inouire_mininet.attachment_locator.class: Inouire\MininetBundle\Service\AttachmentLocator
    inouire_mininet.thumbnailer.class: Inouire\MininetBundle\Service\Thumbnailer
    inouire_mininet.image_resize.class: Inouire\MininetBundle\Service\ImageResize
    inouire_mininet.image_upload.class: Inouire\MininetBundle\Service\ImageUpload
    inouire_mininet.sharelink_checker.class: Inouire\MininetBundle\Service\ShareLinkChecker

services:
    inouire.attachment_locator:
        class: "%inouire_mininet.attachment_locator.class%"
        arguments:
            - "%images_path%"
            - "%videos_path%"
        
    inouire.thumbnailer:
        class: "%inouire_mininet.thumbnailer.class%"
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "@inouire.attachment_locator"
            
    inouire.image_resize:
        class: "%inouire_mininet.image_resize.class%"
        arguments:
            - "@inouire.attachment_locator"
        
    inouire.image_upload:
        class: "%inouire_mininet.image_upload.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@inouire.image_resize"
            - "@inouire.thumbnailer"
            - "@inouire.attachment_locator"
            
    inouire.sharelink_checker:
        class: "%inouire_mininet.sharelink_checker.class%"
        arguments:
            - "@doctrine.orm.entity_manager"

    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }
